# Generated by Django 3.1.4 on 2021-01-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryPhotos',
            new_name='GalleryPhoto',
        ),
    ]
