# Generated by Django 3.1.4 on 2021-01-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0002_auto_20210110_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
