# Generated by Django 3.1.4 on 2021-01-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0003_auto_20210110_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
