# Generated by Django 3.1.4 on 2021-01-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0006_auto_20210111_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='Pass the url here', max_length=1000, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(help_text='Upper Limit : 500 characters', max_length=600, null=True)),
                ('date', models.CharField(help_text='DayS Mon YYYY, Ex: 9th Dec 2020', max_length=30, null=True)),
            ],
        ),
    ]
