# Generated by Django 3.1.4 on 2021-01-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readMore',
            field=models.CharField(blank=True, help_text='Pass the url here', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, help_text='Pass the url here', max_length=1000, null=True),
        ),
    ]
