# Generated by Django 3.1.4 on 2021-01-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0009_auto_20210111_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='date',
            field=models.DateField(help_text='DD/MM/YYYY'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(help_text='DD/MM/YYYY'),
        ),
    ]
