# Generated by Django 3.1.4 on 2021-01-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0011_auto_20210111_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(help_text='Upper Limit : 150 characters', max_length=200, null=True)),
                ('place', models.CharField(help_text='City/District, State', max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.CharField(help_text='Pass the url here', max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='image_url',
            field=models.CharField(help_text='Pass the url here', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, help_text='Pass the url here', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='description',
            field=models.TextField(help_text='Upper Limit : 300 characters', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
