# Generated by Django 3.1.4 on 2021-01-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0012_auto_20210111_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image_url',
            field=models.CharField(blank=True, help_text='Pass the url here', max_length=1000, null=True),
        ),
    ]
