# Generated by Django 3.1.4 on 2021-01-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nirvata', '0013_auto_20210111_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('date',)},
        ),
    ]
